spring.application.name=proyectoejemplo

# Cambiar el puerto interno del contenedor al estándar de Spring
server.port=${PORT:8080}

# Host dinámico inyectado desde el pipeline
app.public-host=${PUBLIC_HOST_URL:http://localhost:8080}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
